Add probe_sysroot_crate and emit_sysroot_crate
cuviper/autocfg pull request #9
Opened 2019-08-16 21:21 UTC by leo60228

See <https://github.com/bluss/indexmap/pull/95#issuecomment-522152651>.

2019-08-17 00:02 UTC, cuviper requested changes
Thanks! Just a few minor tweaks, please.

2019-08-17 00:02 UTC, cuviper commented on src/lib.rs
> +    /// extern crate CRATE as dummy; // `as _` wasn't stabilized until Rust 1.33
Let's use `as probe` for consistency with the trait and type probes.
(also avoiding negative connotations of "dummy")

The comment about `as _` can go in the implementation, rather than showing up in documentation.

2019-08-17 00:02 UTC, cuviper commented on src/lib.rs
> +    /// Emits a config value `has_PATH` if `probe_sysroot_crate` returns true.
```suggestion
    /// Emits a config value `has_CRATE` if `probe_sysroot_crate` returns true.
```

2019-08-17 00:02 UTC, cuviper commented on src/lib.rs
> +    /// `_` in the generated config value.
Let's remove this mangling note, even if we still do it. Crates should always be identifiers anyway...

2019-08-19 19:25 UTC, cuviper approved these changes

2019-08-19 19:33 UTC, merged

2019-08-19 19:36 UTC, cuviper commented
Thanks again -- I've published autocfg 0.1.6.

2019-08-24 09:20 UTC, gnzlbg commented
I suspect this causes a segfault that breaks `libc` crate CI on x86_64-unknown-freebsd: https://cirrus-ci.com/task/6196089037783040

2019-08-24 17:57 UTC, cuviper commented
> I suspect this (the 0.1.6 release) causes a segfault

That would be really weird, since there's no `unsafe`, and this PR should just be dead code if you're not using it. But it seems you've now identified a different root cause in rust-lang/libc#1489.